server:
  port: 9099


spring:
  application:
    name: sword

  redis:
    database: 7
    host: 39.102.78.46
    port: 6379
    password: 123520
    timeout: 6000ms
    lettuce:
      pool:
        max-active: 1000 #最大连接
        max-idle: 100 #最大空闲
        min-idle: 50 #最小空闲连接数


  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://39.98.126.186:3306/lz-sword?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: mysql
    password: P@ssw0rd2020
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: true

# 验证码配置
kaptcha:
  enable: true
  border:
    enabled: yes
    color: black
    thickness: 1
  producer:
    impl: com.lz.sword.common.kaptcha.MyProducer
  wordrenderer:
    impl: com.lz.sword.common.kaptcha.MyWordRenderer
  noise:
    impl: com.lz.sword.common.kaptcha.MyNoise
    color: 0,0,0
  textproducer:
    impl: com.google.code.kaptcha.text.impl.DefaultTextCreator
    char:
      string: 23456789
      length: 4
      space: 10
    font:
      names: Arial
      size: 60
      color: black
  obscurificator:
    impl: com.google.code.kaptcha.impl.WaterRipple
  background:
    impl: com.google.code.kaptcha.impl.DefaultBackground
    clear:
      from: lightGray
      to: white
  image:
    width: 200
    height: 80

sword:
  record-log:
    enable: true

logging:
  config: classpath:logback-spring.xml
  file:
    path: /home/logs/${spring.application.name}
    name: ${spring.application.name}
  level:
    root: info
    com.lz.sword: debug
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: trace
    org.springframework: info
    io.swagger: error

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
    logfile:
      external-file: /home/logs/${spring.application.name}/${spring.application.name}.log
